version: '3.8'
services:
  comfyui:
    image: comfyui:latest
    container_name: comfyui-0.4
    restart: unless-stopped
    ports:
      - "8188:8188"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - E:/AI-T8-video-onekey-20250515/ComfyUI/models:/app/models
      - E:/AI-T8-video-onekey-20250515/ComfyUI/input:/app/input
      - E:/AI-T8-video-onekey-20250515/ComfyUI/output:/app/output
    entrypoint: ["python", "main.py"]
    command: ["--listen", "--port", "8188", "--preview-method", "auto"]